<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eshaan Mathakari">

<title>hw-03-01-eshaanmathakari</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw-03-01-eshaanmathakari_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw-03-01-eshaanmathakari_files/libs/quarto-html/quarto.js"></script>
<script src="hw-03-01-eshaanmathakari_files/libs/quarto-html/popper.min.js"></script>
<script src="hw-03-01-eshaanmathakari_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw-03-01-eshaanmathakari_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw-03-01-eshaanmathakari_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw-03-01-eshaanmathakari_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw-03-01-eshaanmathakari_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw-03-01-eshaanmathakari_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw-03-01-eshaanmathakari_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">hw-03-01-eshaanmathakari</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eshaan Mathakari </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="classification-basic-concepts-and-techniques" class="level1">
<h1>Classification: Basic Concepts and Techniques</h1>
<section id="install-packages" class="level2">
<h2 class="anchored" data-anchor-id="install-packages">Install packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(pacman))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, rpart, rpart.plot, caret, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  lattice, sampling, pROC, mlbench)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data includes information about various artists, their artworks, and related details, such as their gender, nationality, race, and the museums where their work is counted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>artists <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-17/artists.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(artists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  artist_name   edition_number  year artist_nationality artist_nationality_other
  &lt;chr&gt;                  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;                   
1 Aaron Douglas              9  1991 American           American                
2 Aaron Douglas             10  1996 American           American                
3 Aaron Douglas             11  2001 American           American                
4 Aaron Douglas             12  2005 American           American                
5 Aaron Douglas             13  2009 American           American                
6 Aaron Douglas             14  2013 American           American                
# ℹ 9 more variables: artist_gender &lt;chr&gt;, artist_race &lt;chr&gt;,
#   artist_ethnicity &lt;chr&gt;, book &lt;chr&gt;, space_ratio_per_page_total &lt;dbl&gt;,
#   artist_unique_id &lt;dbl&gt;, moma_count_to_year &lt;dbl&gt;,
#   whitney_count_to_year &lt;dbl&gt;, artist_race_nwi &lt;chr&gt;</code></pre>
</div>
</div>
<p>A <code>tibble</code> is a data structure in R, part of the tidyverse ecosystem, that is designed to make data manipulation and analysis easier and more consistent. It is an enhanced and modern alternative to the traditional data frame in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the artists dataset into a tibble.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>(artists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,162 × 14
   artist_name    edition_number  year artist_nationality artist_nationality_o…¹
   &lt;chr&gt;                   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;                 
 1 Aaron Douglas               9  1991 American           American              
 2 Aaron Douglas              10  1996 American           American              
 3 Aaron Douglas              11  2001 American           American              
 4 Aaron Douglas              12  2005 American           American              
 5 Aaron Douglas              13  2009 American           American              
 6 Aaron Douglas              14  2013 American           American              
 7 Aaron Douglas              15  2016 American           American              
 8 Aaron Douglas              16  2020 American           American              
 9 Adélaïde Labi…             14  2013 French             French                
10 Adélaïde Labi…             15  2016 French             French                
# ℹ 3,152 more rows
# ℹ abbreviated name: ¹​artist_nationality_other
# ℹ 9 more variables: artist_gender &lt;chr&gt;, artist_race &lt;chr&gt;,
#   artist_ethnicity &lt;chr&gt;, book &lt;chr&gt;, space_ratio_per_page_total &lt;dbl&gt;,
#   artist_unique_id &lt;dbl&gt;, moma_count_to_year &lt;dbl&gt;,
#   whitney_count_to_year &lt;dbl&gt;, artist_race_nwi &lt;chr&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of columns to be removed</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>columns_to_remove <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'artist_name'</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the specified columns</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>artists <span class="ot">&lt;-</span> <span class="fu">select</span>(artists, <span class="sc">-</span><span class="fu">one_of</span>(columns_to_remove))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(artists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  edition_number  year artist_nationality artist_nationality_other artist_gender
           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;                    &lt;chr&gt;        
1              9  1991 American           American                 Male         
2             10  1996 American           American                 Male         
3             11  2001 American           American                 Male         
4             12  2005 American           American                 Male         
5             13  2009 American           American                 Male         
6             14  2013 American           American                 Male         
# ℹ 8 more variables: artist_race &lt;chr&gt;, artist_ethnicity &lt;chr&gt;, book &lt;chr&gt;,
#   space_ratio_per_page_total &lt;dbl&gt;, artist_unique_id &lt;dbl&gt;,
#   moma_count_to_year &lt;dbl&gt;, whitney_count_to_year &lt;dbl&gt;,
#   artist_race_nwi &lt;chr&gt;</code></pre>
</div>
</div>
<p>Removing irrelevant columns for prediction: <code>artist_name</code> because the artist’s name itself might not be a strong predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>artists <span class="ot">&lt;-</span> artists <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert logical columns to factors with levels 'TRUE' and 'FALSE'.</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.logical), factor, <span class="at">levels =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert character columns to factors.</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), factor))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we will transform logical columns to factors with specific levels and character columns to factors in a data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(artists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> edition_number        year      artist_nationality artist_nationality_other
 Min.   : 1.000   Min.   :1926   American:908       American:908            
 1st Qu.: 5.000   1st Qu.:1986   French  :870       British :317            
 Median : 8.000   Median :1996   British :317       French  :870            
 Mean   : 8.223   Mean   :1994   German  :256       German  :256            
 3rd Qu.:12.000   3rd Qu.:2009   Spanish : 94       Other   :717            
 Max.   :16.000   Max.   :2020   Italian : 74       Spanish : 94            
                                 (Other) :643                               
 artist_gender                                    artist_race  
 Female: 342   American Indian or Alaska Native         :  12  
 Male  :2762   Asian                                    :  79  
 N/A   :  58   Black or African American                :  83  
               N/A                                      :  29  
               Native Hawaiian or Other Pacific Islander:  23  
               White                                    :2936  
                                                               
                      artist_ethnicity      book     
 Hispanic or Latino origin    : 158    Gardner:1943  
 Not Hispanic or Latino origin:2946    Janson :1219  
 NA's                         :  58                  
                                                     
                                                     
                                                     
                                                     
 space_ratio_per_page_total artist_unique_id moma_count_to_year
 Min.   :0.0946             Min.   :  1.0    Min.   : 0.000    
 1st Qu.:0.3082             1st Qu.:108.0    1st Qu.: 0.000    
 Median :0.4093             Median :189.0    Median : 1.000    
 Mean   :0.5301             Mean   :201.8    Mean   : 4.306    
 3rd Qu.:0.5941             3rd Qu.:305.8    3rd Qu.: 5.000    
 Max.   :3.7967             Max.   :413.0    Max.   :64.000    
                                                               
 whitney_count_to_year  artist_race_nwi
 Min.   : 0.000        Non-White: 226  
 1st Qu.: 0.000        White    :2936  
 Median : 0.000                        
 Mean   : 1.957                        
 3rd Qu.: 0.000                        
 Max.   :40.000                        
                                       </code></pre>
</div>
</div>
<p>Checking for missing values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values in the dataset</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(artists))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            edition_number                       year 
                         0                          0 
        artist_nationality   artist_nationality_other 
                         0                          0 
             artist_gender                artist_race 
                         0                          0 
          artist_ethnicity                       book 
                        58                          0 
space_ratio_per_page_total           artist_unique_id 
                         0                          0 
        moma_count_to_year      whitney_count_to_year 
                         0                          0 
           artist_race_nwi 
                         0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove rows with missing values </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>artists <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(artists)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(artists))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            edition_number                       year 
                         0                          0 
        artist_nationality   artist_nationality_other 
                         0                          0 
             artist_gender                artist_race 
                         0                          0 
          artist_ethnicity                       book 
                         0                          0 
space_ratio_per_page_total           artist_unique_id 
                         0                          0 
        moma_count_to_year      whitney_count_to_year 
                         0                          0 
           artist_race_nwi 
                         0 </code></pre>
</div>
</div>
</section>
<section id="decision-trees" class="level2">
<h2 class="anchored" data-anchor-id="decision-trees">Decision Trees</h2>
<p>Recursive Partitioning (similar to CART) uses the Gini index to make splitting decisions and early stopping (pre-pruning).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="create-tree-with-default-settings-uses-pre-pruning" class="level3">
<h3 class="anchored" data-anchor-id="create-tree-with-default-settings-uses-pre-pruning">Create Tree With Default Settings (uses pre-pruning)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a decision tree with default settings</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tree_default <span class="ot">&lt;-</span> artists <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rpart</span>(book <span class="sc">~</span> ., <span class="at">data =</span> _)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>tree_default</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n= 3104 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

 1) root 3104 1219 Gardner (0.6072809 0.3927191)  
   2) edition_number&gt;=8.5 1303    0 Gardner (1.0000000 0.0000000) *
   3) edition_number&lt; 8.5 1801  582 Janson (0.3231538 0.6768462)  
     6) year&lt; 1988.5 954  372 Gardner (0.6100629 0.3899371)  
      12) edition_number&gt;=3.5 459    0 Gardner (1.0000000 0.0000000) *
      13) edition_number&lt; 3.5 495  123 Janson (0.2484848 0.7515152)  
        26) year&lt; 1955.5 123    0 Gardner (1.0000000 0.0000000) *
        27) year&gt;=1955.5 372    0 Janson (0.0000000 1.0000000) *
     7) year&gt;=1988.5 847    0 Janson (0.0000000 1.0000000) *</code></pre>
</div>
</div>
<p>Here we will try to predict whether a particular artist is included in Janson’s History of Art or Gardner’s Art Through the Ages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(tree_default, <span class="at">extra =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="create-a-full-tree" class="level3">
<h3 class="anchored" data-anchor-id="create-a-full-tree">Create a Full Tree</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a decision tree</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>tree_full <span class="ot">&lt;-</span> artists <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rpart</span>(book <span class="sc">~</span> . , <span class="at">data =</span> _, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">2</span>, <span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(tree_full, <span class="at">extra =</span> <span class="dv">2</span>, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">roundint=</span><span class="cn">FALSE</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">box.palette =</span> <span class="fu">list</span>(<span class="st">"Gy"</span>, <span class="st">"Gn"</span>, <span class="st">"Bu"</span>, <span class="st">"Bn"</span>, </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Or"</span>, <span class="st">"Rd"</span>, <span class="st">"Pu"</span>)) <span class="co"># specify 7 colors</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When <code>cp = 0</code>This means that no cost complexity pruning is applied. In other words, the tree is allowed to grow until it perfectly fits the training data, which can result in a very complex, deep, and overfit tree.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>tree_full</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n= 3104 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

 1) root 3104 1219 Gardner (0.6072809 0.3927191)  
   2) edition_number&gt;=8.5 1303    0 Gardner (1.0000000 0.0000000) *
   3) edition_number&lt; 8.5 1801  582 Janson (0.3231538 0.6768462)  
     6) year&lt; 1988.5 954  372 Gardner (0.6100629 0.3899371)  
      12) edition_number&gt;=3.5 459    0 Gardner (1.0000000 0.0000000) *
      13) edition_number&lt; 3.5 495  123 Janson (0.2484848 0.7515152)  
        26) year&lt; 1955.5 123    0 Gardner (1.0000000 0.0000000) *
        27) year&gt;=1955.5 372    0 Janson (0.0000000 1.0000000) *
     7) year&gt;=1988.5 847    0 Janson (0.0000000 1.0000000) *</code></pre>
</div>
</div>
<p>Training error on tree with pre-pruning Here we are making predictions using a decision tree model (<code>tree_default</code>) on the <code>artists</code> data frame</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict book using the decision tree model</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(tree_default, artists ) <span class="sc">|&gt;</span> <span class="fu">head</span> ()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Gardner Janson
1       1      0
2       1      0
3       1      0
4       1      0
5       1      0
6       1      0</code></pre>
</div>
</div>
<p>Predicts the book for each record in the ‘artists’ dataset, which is either “Gardner” (1) or “Janson” (0).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict class labels (Gardner or Janson)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(tree_default, artists , <span class="at">type=</span><span class="st">"class"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      1       2       3       4       5       6 
Gardner Gardner Gardner Gardner Gardner Gardner 
Levels: Gardner Janson</code></pre>
</div>
</div>
<p>By specifying <code>type = "class"</code>, you obtain the class labels that the decision tree model predicts for each observation in the <code>artists</code> data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>confusion_table <span class="ot">&lt;-</span> <span class="fu">with</span>(artists, <span class="fu">table</span>(book , pred))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>confusion_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         pred
book      Gardner Janson
  Gardner    1885      0
  Janson        0   1219</code></pre>
</div>
</div>
<p>The model correctly predicted “Gardner” 1885 times (True Positives) and “Janson” 1219 times (True Negatives). There were <code>no False Positives or False Negatives</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total number of correct predictions</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>correct <span class="ot">&lt;-</span> confusion_table <span class="sc">|&gt;</span> <span class="fu">diag</span>() <span class="sc">|&gt;</span> <span class="fu">sum</span>()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>correct</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3104</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total number of errors</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> confusion_table <span class="sc">|&gt;</span> <span class="fu">sum</span>() <span class="sc">-</span> correct</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>error</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> correct <span class="sc">/</span> (correct <span class="sc">+</span> error)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Using a function for accuracy</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="cf">function</span>(truth, prediction) {</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(truth, prediction)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(<span class="fu">diag</span>(tbl))<span class="sc">/</span><span class="fu">sum</span>(tbl)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(artists <span class="sc">|&gt;</span> <span class="fu">pull</span>(book), pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Training error of the full tree</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(artists <span class="sc">|&gt;</span> <span class="fu">pull</span>(book), </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">predict</span>(tree_full, artists, <span class="at">type =</span> <span class="st">"class"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="make-predictions-for-new-data" class="level3">
<h3 class="anchored" data-anchor-id="make-predictions-for-new-data">Make Predictions for New Data</h3>
<p>Making our own artist: Artist in year 2020 with edition number 17.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>my_artist <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">edition_number =</span> <span class="dv">17</span> ,<span class="at">year=</span> <span class="dv">2020</span>,<span class="at">artist_nationality =</span> <span class="st">"American"</span>,<span class="at">artist_nationality_other =</span> <span class="st">"Other"</span>,<span class="at">artist_gender =</span> <span class="st">"Female"</span>,<span class="at">artist_race =</span> <span class="st">"Black or African American"</span>,<span class="at">artist_ethnicity =</span> <span class="st">"Not Hispanic or Latino origin"</span>, <span class="at">book =</span> <span class="cn">NA</span>, <span class="at">space_ratio_per_page_total =</span> <span class="fl">0.5344869907</span>,<span class="at">artist_unique_id =</span> <span class="dv">10</span>,<span class="at">moma_count_to_year =</span> <span class="dv">15</span>,<span class="at">whitney_count_to_year =</span> <span class="dv">5</span>,<span class="at">artist_race_nwi =</span> <span class="st">"Non-White"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fix columns to be factors like in the training set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert character columns in my_artist to factors</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>my_artist <span class="ot">&lt;-</span> my_artist <span class="sc">|&gt;</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), factor))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>my_artist</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 13
  edition_number  year artist_nationality artist_nationality_other artist_gender
           &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;              &lt;fct&gt;                    &lt;fct&gt;        
1             17  2020 American           Other                    Female       
# ℹ 8 more variables: artist_race &lt;fct&gt;, artist_ethnicity &lt;fct&gt;, book &lt;lgl&gt;,
#   space_ratio_per_page_total &lt;dbl&gt;, artist_unique_id &lt;dbl&gt;,
#   moma_count_to_year &lt;dbl&gt;, whitney_count_to_year &lt;dbl&gt;,
#   artist_race_nwi &lt;fct&gt;</code></pre>
</div>
</div>
<p>Make a prediction using the default tree</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(tree_default , my_artist, <span class="at">type =</span> <span class="st">"class"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      1 
Gardner 
Levels: Gardner Janson</code></pre>
</div>
</div>
</section>
</section>
<section id="model-evaluation-with-caret" class="level2">
<h2 class="anchored" data-anchor-id="model-evaluation-with-caret">Model Evaluation with Caret</h2>
<p>The package <code>caret</code> makes preparing training sets, building classification (and regression) models and evaluation easier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Set random number generator seed to make results reproducible</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="hold-out-test-data" class="level3">
<h3 class="anchored" data-anchor-id="hold-out-test-data">Hold out Test Data</h3>
<p>Test data is not used in the model building process and set aside purely for testing the model. Here, we partition data the 80% training and 20% testing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data partition</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>inTrain <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(<span class="at">y =</span> artists<span class="sc">$</span>book, <span class="at">p =</span> .<span class="dv">8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the training set</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>artists_train <span class="ot">&lt;-</span> artists <span class="sc">|&gt;</span> <span class="fu">slice</span>(inTrain)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the testing set</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>artists_test <span class="ot">&lt;-</span> artists <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="sc">-</span>inTrain)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="learn-a-model-and-tune-hyperparameters-on-the-training-data" class="level3">
<h3 class="anchored" data-anchor-id="learn-a-model-and-tune-hyperparameters-on-the-training-data">Learn a Model and Tune Hyperparameters on the Training Data</h3>
<p>The package caret combines training and validation for <code>hyperparameter</code> tuning into a single function called <code>train()</code>. It internally splits the data into training and validation sets and thus will provide you with error estimates for different hyperparameter settings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> artists_train <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> _ ,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">2</span>),</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">tuneLength =</span> <span class="dv">5</span>)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

2484 samples
  12 predictor
   2 classes: 'Gardner', 'Janson' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 2236, 2236, 2235, 2236, 2235, 2236, ... 
Resampling results across tuning parameters:

  cp         Accuracy   Kappa    
  0.0000000  1.0000000  1.0000000
  0.1298668  0.9605404  0.9188247
  0.2597336  0.8111942  0.6354258
  0.3896004  0.8111942  0.6354258
  0.5194672  0.7009726  0.3035893

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.</code></pre>
</div>
</div>
<p>In this case, the model with <code>cp = 0</code> was selected as the final model due to its perfect accuracy on the training data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit<span class="sc">$</span>finalModel, <span class="at">extra =</span> <span class="dv">2</span>,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">box.palette =</span> <span class="fu">list</span>(<span class="st">"Gy"</span>, <span class="st">"Gn"</span>, <span class="st">"Bu"</span>, <span class="st">"Bn"</span>, <span class="st">"Or"</span>, <span class="st">"Rd"</span>, <span class="st">"Pu"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute variable importance </span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">varImp</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rpart variable importance

  only 20 most important variables shown (out of 72)

                                    Overall
edition_number                     100.0000
year                                79.6051
space_ratio_per_page_total          18.7366
moma_count_to_year                   3.7772
artist_raceAsian                     1.9624
artist_nationalityJapanese           1.5568
artist_nationalityFrench             1.3456
artist_nationalityMexican            0.4140
artist_nationalityHungarian-French   0.3783
artist_nationalityArgentine          0.0000
artist_nationalityItalian            0.0000
artist_nationality_otherGerman       0.0000
`artist_nationalityN/A`              0.0000
artist_nationalityCzech              0.0000
artist_unique_id                     0.0000
`artist_nationalityRussian-French`   0.0000
`artist_nationalitySwiss-German`     0.0000
`artist_raceN/A`                     0.0000
`artist_nationalityDanish-French`    0.0000
artist_nationalityRussian            0.0000</code></pre>
</div>
</div>
<p>Here is the variable importance without competing splits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute variable importance</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a> imp <span class="ot">&lt;-</span> <span class="fu">varImp</span>(fit, <span class="at">compete =</span> <span class="cn">FALSE</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a> imp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rpart variable importance

  only 20 most important variables shown (out of 71)

                                       Overall
edition_number                          100.00
year                                     53.84
artist_unique_id                          0.00
`artist_nationalityPakistani-American`    0.00
artist_nationalityHungarian               0.00
artist_nationalityBelgian                 0.00
artist_nationalityPeruvian                0.00
artist_nationalityPolynesian              0.00
artist_nationalityCanadian                0.00
`artist_nationalityHungarian-French`      0.00
artist_nationalityAustralian              0.00
artist_genderMale                         0.00
artist_nationalityMexican                 0.00
artist_nationalityJapanese                0.00
moma_count_to_year                        0.00
`artist_nationalityItalian-American`      0.00
`artist_nationalityGerman-American`       0.00
artist_nationalityAustrian                0.00
artist_nationalityKorean                  0.00
artist_nationalityCzech                   0.00</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>edition_number has the highest importance score, represented as 100.00. year has an importance score of 53.84, indicating it is also a significant predictor. The other predictor variables listed have importance scores of 0.00, suggesting they have little to no impact on the model’s predictive performance.</p>
</section>
</section>
<section id="testing-confusion-matrix-and-confidence-interval-for-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="testing-confusion-matrix-and-confidence-interval-for-accuracy">Testing: Confusion Matrix and Confidence Interval for Accuracy</h2>
<p>Use the best model on the test data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on test data</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> artists_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate a confusion matrix</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> pred, </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">ref =</span> artists_test <span class="sc">|&gt;</span> <span class="fu">pull</span>(book))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Gardner Janson
   Gardner     377      0
   Janson        0    243
                                     
               Accuracy : 1          
                 95% CI : (0.9941, 1)
    No Information Rate : 0.6081     
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
                                     
                  Kappa : 1          
                                     
 Mcnemar's Test P-Value : NA         
                                     
            Sensitivity : 1.0000     
            Specificity : 1.0000     
         Pos Pred Value : 1.0000     
         Neg Pred Value : 1.0000     
             Prevalence : 0.6081     
         Detection Rate : 0.6081     
   Detection Prevalence : 0.6081     
      Balanced Accuracy : 1.0000     
                                     
       'Positive' Class : Gardner    
                                     </code></pre>
</div>
</div>
<p>The accuracy is <code>1.0</code>,Sensitivity (True Positive Rate) and Specificity (True Negative Rate) are also both <code>1.0</code>, indicating perfect performance.</p>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">Model Comparison</h2>
<p>We will compare decision trees with a <code>k-nearest neighbors (kNN)</code> classifier. We will create fixed sampling scheme (10-folds) so we compare the different models using exactly the same folds. It is specified as <code>trControl</code> during training.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create cross-validation folds</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">createFolds</span>(artists_train<span class="sc">$</span>book, <span class="at">k =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Build models</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a classification model using the "rpart"</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>rpartFit <span class="ot">&lt;-</span> artists_train <span class="sc">|&gt;</span> </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">tuneLength =</span> <span class="dv">10</span>,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">indexOut =</span> train_index)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>KNN fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>knnFit <span class="ot">&lt;-</span> artists_train <span class="sc">|&gt;</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"knn"</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">preProcess =</span> <span class="st">"scale"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">tuneLength =</span> <span class="dv">10</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">indexOut =</span> train_index)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare accuracy over all folds.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>resamps <span class="ot">&lt;-</span> <span class="fu">resamples</span>(<span class="fu">list</span>(</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">CART =</span> rpartFit,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">kNearestNeighbors =</span> knnFit</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>       ))</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(resamps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
summary.resamples(object = resamps)

Models: CART, kNearestNeighbors 
Number of resamples: 10 

Accuracy 
                       Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
CART              1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
kNearestNeighbors 0.9435484 0.9485887 0.9577423 0.9609324 0.9768469 0.9799197
                  NA's
CART                 0
kNearestNeighbors    0

Kappa 
                       Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
CART              1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
kNearestNeighbors 0.8787963 0.8925138 0.9109738 0.9177668 0.9513072 0.9580087
                  NA's
CART                 0
kNearestNeighbors    0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(resamps, <span class="at">layout =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here “CART achieving perfect accuracy and Kappa, while kNearestNeighbors also has strong performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the differences in performance metrics between two models</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>difs <span class="ot">&lt;-</span> <span class="fu">diff</span>(resamps)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>difs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
diff.resamples(x = resamps)

Models: CART, kNearestNeighbors 
Metrics: Accuracy, Kappa 
Number of differences: 1 
p-value adjustment: bonferroni </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(difs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
summary.diff.resamples(object = difs)

p-value adjustment: bonferroni 
Upper diagonal: estimates of the difference
Lower diagonal: p-value for H0: difference = 0

Accuracy 
                  CART      kNearestNeighbors
CART                        0.03907          
kNearestNeighbors 1.754e-05                  

Kappa 
                  CART      kNearestNeighbors
CART                        0.08223          
kNearestNeighbors 1.852e-05                  </code></pre>
</div>
</div>
</section>
<section id="feature-selection-and-feature-preparation" class="level2">
<h2 class="anchored" data-anchor-id="feature-selection-and-feature-preparation">Feature Selection and Feature Preparation</h2>
<p>Decision trees implicitly select features for splitting, but we can also select features manually.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FSelector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="univariate-feature-importance-score" class="level3">
<h3 class="anchored" data-anchor-id="univariate-feature-importance-score">Univariate Feature Importance Score</h3>
<p>These scores measure how related each feature is to the class variable. For discrete features (as in our case), the chi-square statistic can be used to derive a score.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>weights <span class="ot">&lt;-</span> artists_train<span class="sc">|&gt;</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">chi.squared</span>(book <span class="sc">~</span> ., <span class="at">data =</span> _) <span class="sc">|&gt;</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">"feature"</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(attr_importance))</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>weights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   feature                    attr_importance
   &lt;chr&gt;                                &lt;dbl&gt;
 1 year                                0.831 
 2 edition_number                      0.692 
 3 space_ratio_per_page_total          0.299 
 4 artist_nationality                  0.241 
 5 artist_race                         0.131 
 6 artist_race_nwi                     0.0976
 7 artist_nationality_other            0.0435
 8 artist_ethnicity                    0.0388
 9 artist_gender                       0.0280
10 artist_unique_id                    0     
11 moma_count_to_year                  0     
12 whitney_count_to_year               0     </code></pre>
</div>
</div>
<p>Provides insight into the importance of each feature in predicting the <code>book</code> categories and can help in feature selection or understanding which features are most relevant in the classification task.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(weights,</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> attr_importance, <span class="at">y =</span> <span class="fu">reorder</span>(feature, attr_importance))) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Importance score"</span>) <span class="sc">+</span> </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Feature"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><code>year</code> has the highest importance score , indicating that it is a significant predictor and ‘edition_number’ follows with a relatively high importance score.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>subset <span class="ot">&lt;-</span> <span class="fu">cutoff.k</span>(weights <span class="sc">|&gt;</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">column_to_rownames</span>(<span class="st">"feature"</span>), <span class="dv">5</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>subset</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "year"                       "edition_number"            
[3] "space_ratio_per_page_total" "artist_nationality"        
[5] "artist_race"               </code></pre>
</div>
</div>
<p>Getting the 5 best features Use only the best 5 features to build a model (<code>Fselector</code> provides <code>as.simple.formula</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">as.simple.formula</span>(subset, <span class="st">"book"</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>f</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>book ~ year + edition_number + space_ratio_per_page_total + artist_nationality + 
    artist_race
&lt;environment: 0x109907388&gt;</code></pre>
</div>
</div>
<p>“year,” “edition_number,” “space_ratio_per_page_total,” “artist_nationality,” and “artist_race.” are used as predictors in the modeling or analysis of the “book” variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> artists_train <span class="sc">|&gt;</span> <span class="fu">rpart</span>(f, <span class="at">data =</span> _)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(m, <span class="at">extra =</span> <span class="dv">2</span>, <span class="at">roundint =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>artists_train <span class="sc">|&gt;</span> </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gain.ratio</span>(book <span class="sc">~</span> ., <span class="at">data =</span> _) <span class="sc">|&gt;</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">"feature"</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(attr_importance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   feature                    attr_importance
   &lt;chr&gt;                                &lt;dbl&gt;
 1 edition_number                    0.353   
 2 year                              0.188   
 3 space_ratio_per_page_total        0.0476  
 4 artist_race                       0.0466  
 5 artist_race_nwi                   0.0254  
 6 artist_nationality                0.0160  
 7 artist_ethnicity                  0.00408 
 8 artist_gender                     0.00115 
 9 artist_nationality_other          0.000592
10 artist_unique_id                  0       
11 moma_count_to_year                0       
12 whitney_count_to_year             0       </code></pre>
</div>
</div>
</section>
<section id="feature-subset-selection" class="level3">
<h3 class="anchored" data-anchor-id="feature-subset-selection">Feature Subset Selection</h3>
<p>Often features are related and calculating importance for each feature independently is not optimal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>artists_train <span class="sc">|&gt;</span> </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cfs</span>(book <span class="sc">~</span> ., <span class="at">data =</span> _)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "edition_number" "year"          </code></pre>
</div>
</div>
<p><code>edition_number</code> and <code>year</code> are the two predictor variables selected by the CFS method.</p>
<p><code>Black</code>-box feature selection uses an evaluator function (the black box) to calculate a score to be maximized. We define an evaluation function that builds a model given a subset of features and calculates a quality score.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>evaluator <span class="ot">&lt;-</span> <span class="cf">function</span>(subset) {</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  model <span class="ot">&lt;-</span> artists_train<span class="sc">|&gt;</span> </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">train</span>(<span class="fu">as.simple.formula</span>(subset, <span class="st">"book"</span>),</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> _,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"boot"</span>, <span class="at">number =</span> <span class="dv">5</span>),</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">tuneLength =</span> <span class="dv">0</span>)</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  results <span class="ot">&lt;-</span> model<span class="sc">$</span>resample<span class="sc">$</span>Accuracy</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Trying features:"</span>, <span class="fu">paste</span>(subset, <span class="at">collapse =</span> <span class="st">" + "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">mean</span>(results)</span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Accuracy:"</span>, <span class="fu">round</span>(m, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  m</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>features <span class="ot">&lt;-</span> artists_train <span class="sc">|&gt;</span> <span class="fu">colnames</span>() <span class="sc">|&gt;</span> <span class="fu">setdiff</span>(<span class="st">"type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-dummy-variables-for-factors" class="level3">
<h3 class="anchored" data-anchor-id="using-dummy-variables-for-factors">Using Dummy Variables for Factors</h3>
<p>Nominal features (factors) are often encoded as a series of 0-1 dummy variables. First we use the original encoding of type as a factor with several values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>tree_predator <span class="ot">&lt;-</span> artists_train <span class="sc">|&gt;</span> </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rpart</span>(artist_nationality  <span class="sc">~</span> book, <span class="at">data =</span> _)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(tree_predator, <span class="at">extra =</span> <span class="dv">2</span>, <span class="at">roundint =</span> <span class="cn">FALSE</span>, <span class="at">box.palette=</span><span class="st">"Blues"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Convert type into a set of 0-1 dummy variables using class2ind.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>artists_train_dummy <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">class2ind</span>(artists_train<span class="sc">$</span>book)) <span class="sc">|&gt;</span> </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), as.factor)) <span class="sc">|&gt;</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_column</span>(<span class="at">artist_nationality =</span> artists_train<span class="sc">$</span>artist_nationality)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>artists_train_dummy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,484 × 3
   Gardner Janson artist_nationality
   &lt;fct&gt;   &lt;fct&gt;  &lt;fct&gt;             
 1 1       0      American          
 2 1       0      American          
 3 1       0      American          
 4 1       0      American          
 5 1       0      French            
 6 1       0      French            
 7 1       0      French            
 8 1       0      French            
 9 1       0      French            
10 1       0      French            
# ℹ 2,474 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>tree_artist_nationality <span class="ot">&lt;-</span> artists_train_dummy <span class="sc">|&gt;</span> </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rpart</span>(artist_nationality <span class="sc">~</span> ., </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">2</span>, <span class="at">cp =</span> <span class="fl">0.01</span>))</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(tree_artist_nationality, <span class="at">roundint =</span> <span class="cn">FALSE</span>, <span class="at">box.palette =</span> <span class="fu">list</span>(<span class="st">"Gy"</span>, <span class="st">"Gn"</span>, <span class="st">"Bu"</span>, <span class="st">"Bn"</span>, <span class="st">"Or"</span>, <span class="st">"Rd"</span>, <span class="st">"Pu"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> artists_train <span class="sc">|&gt;</span> </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(artist_race_nwi <span class="sc">~</span> book, </span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _, </span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">2</span>),</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">cp =</span> <span class="fl">0.01</span>))</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

2484 samples
   1 predictor
   2 classes: 'Non-White', 'White' 

No pre-processing
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 2484, 2484, 2484, 2484, 2484, 2484, ... 
Resampling results:

  Accuracy   Kappa
  0.9466562  0    

Tuning parameter 'cp' was held constant at a value of 0.01</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit<span class="sc">$</span>finalModel, <span class="at">extra =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="class-imbalance" class="level2">
<h2 class="anchored" data-anchor-id="class-imbalance">Class Imbalance</h2>
<p>Classifiers have a hard time to learn from data where we have much more observations for one class (called the majority class). This is called the class imbalance problem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Class distribution</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(artists, <span class="fu">aes</span>(<span class="at">y =</span> book)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We already have a imbalanced problem as you can see Gardner instances are more that the Janson</p>
<p>Create test and training data. I use here a 50/50 split.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>inTrain <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(<span class="at">y =</span> artists<span class="sc">$</span>book, <span class="at">p =</span> .<span class="dv">5</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>training_artists <span class="ot">&lt;-</span> artists <span class="sc">|&gt;</span> <span class="fu">slice</span>(inTrain)</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>testing_artists <span class="ot">&lt;-</span> artists <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="sc">-</span>inTrain)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="option-1-use-the-data-as-is-and-hope-for-the-best" class="level3">
<h3 class="anchored" data-anchor-id="option-1-use-the-data-as-is-and-hope-for-the-best">Option 1: Use the Data As Is and Hope For The Best</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> training_artists <span class="sc">|&gt;</span> </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

1553 samples
  12 predictor
   2 classes: 'Gardner', 'Janson' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 1397, 1398, 1398, 1398, 1397, 1398, ... 
Resampling results across tuning parameters:

  cp          Accuracy   Kappa    
  0.09672131  0.9774194  0.9539383
  0.17786885  0.8712159  0.7489398
  0.54754098  0.7057858  0.3113405

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.09672131.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit<span class="sc">$</span>finalModel, <span class="at">extra =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> <span class="fu">predict</span>(fit, testing_artists),</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">ref =</span> testing_artists<span class="sc">$</span>book, <span class="at">positive =</span> <span class="st">"Janson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Gardner Janson
   Gardner     878      0
   Janson       64    609
                                          
               Accuracy : 0.9587          
                 95% CI : (0.9476, 0.9681)
    No Information Rate : 0.6074          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.9151          
                                          
 Mcnemar's Test P-Value : 3.407e-15       
                                          
            Sensitivity : 1.0000          
            Specificity : 0.9321          
         Pos Pred Value : 0.9049          
         Neg Pred Value : 1.0000          
             Prevalence : 0.3926          
         Detection Rate : 0.3926          
   Detection Prevalence : 0.4339          
      Balanced Accuracy : 0.9660          
                                          
       'Positive' Class : Janson          
                                          </code></pre>
</div>
</div>
</section>
<section id="option-2-balance-data-with-resampling" class="level3">
<h3 class="anchored" data-anchor-id="option-2-balance-data-with-resampling">Option 2: Balance Data With Resampling</h3>
<p>We use stratified sampling with replacement (to oversample the minority/positive class).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sampling)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1000</span>) <span class="co"># for repeatability</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>id <span class="ot">&lt;-</span> <span class="fu">strata</span>(training_artists, <span class="at">stratanames =</span> <span class="st">"book"</span>, <span class="at">size =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">50</span>), <span class="at">method =</span> <span class="st">"srswr"</span>)</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>training_artists_balanced <span class="ot">&lt;-</span> training_artists <span class="sc">|&gt;</span> </span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(id<span class="sc">$</span>ID_unit)</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(training_artists_balanced<span class="sc">$</span>book)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Gardner  Janson 
     50      50 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> training_artists_balanced <span class="sc">|&gt;</span> </span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>),</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">5</span>))</span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

100 samples
 12 predictor
  2 classes: 'Gardner', 'Janson' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 90, 90, 90, 90, 90, 90, ... 
Resampling results across tuning parameters:

  cp    Accuracy  Kappa
  0.02  0.99      0.98 
  0.19  0.74      0.48 
  0.52  0.60      0.20 

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.02.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit<span class="sc">$</span>finalModel, <span class="at">extra =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Check on the unbalanced testing data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> <span class="fu">predict</span>(fit, testing_artists),</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">ref =</span> testing_artists<span class="sc">$</span>book, <span class="at">positive =</span> <span class="st">"Janson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Gardner Janson
   Gardner     942      0
   Janson        0    609
                                     
               Accuracy : 1          
                 95% CI : (0.9976, 1)
    No Information Rate : 0.6074     
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
                                     
                  Kappa : 1          
                                     
 Mcnemar's Test P-Value : NA         
                                     
            Sensitivity : 1.0000     
            Specificity : 1.0000     
         Pos Pred Value : 1.0000     
         Neg Pred Value : 1.0000     
             Prevalence : 0.3926     
         Detection Rate : 0.3926     
   Detection Prevalence : 0.3926     
      Balanced Accuracy : 1.0000     
                                     
       'Positive' Class : Janson     
                                     </code></pre>
</div>
</div>
<p>Here <code>Accuracy</code> is 1, indicating perfect accuracy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>id <span class="ot">&lt;-</span> <span class="fu">strata</span>(training_artists, <span class="at">stratanames =</span> <span class="st">"book"</span>, <span class="at">size =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>), <span class="at">method =</span> <span class="st">"srswr"</span>)</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>training_artists_balanced <span class="ot">&lt;-</span> training_artists <span class="sc">|&gt;</span> </span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(id<span class="sc">$</span>ID_unit)</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(training_artists_balanced<span class="sc">$</span>book)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Gardner  Janson 
     50     100 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> training_artists_balanced <span class="sc">|&gt;</span> </span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>),</span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">5</span>))</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> <span class="fu">predict</span>(fit, testing_artists),</span>
<span id="cb108-9"><a href="#cb108-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">ref =</span> testing_artists<span class="sc">$</span>book, <span class="at">positive =</span> <span class="st">"Janson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Gardner Janson
   Gardner     942      0
   Janson        0    609
                                     
               Accuracy : 1          
                 95% CI : (0.9976, 1)
    No Information Rate : 0.6074     
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
                                     
                  Kappa : 1          
                                     
 Mcnemar's Test P-Value : NA         
                                     
            Sensitivity : 1.0000     
            Specificity : 1.0000     
         Pos Pred Value : 1.0000     
         Neg Pred Value : 1.0000     
             Prevalence : 0.3926     
         Detection Rate : 0.3926     
   Detection Prevalence : 0.3926     
      Balanced Accuracy : 1.0000     
                                     
       'Positive' Class : Janson     
                                     </code></pre>
</div>
</div>
</section>
<section id="option-3-build-a-larger-tree-and-use-predicted-probabilities" class="level3">
<h3 class="anchored" data-anchor-id="option-3-build-a-larger-tree-and-use-predicted-probabilities">Option 3: Build A Larger Tree and use Predicted Probabilities</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> training_artists <span class="sc">|&gt;</span> </span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">tuneLength =</span> <span class="dv">10</span>,</span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>,</span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">classProbs =</span> <span class="cn">TRUE</span>,  <span class="do">## necessary for predict with type="prob"</span></span>
<span id="cb110-8"><a href="#cb110-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">summaryFunction=</span>twoClassSummary),  <span class="do">## necessary for ROC</span></span>
<span id="cb110-9"><a href="#cb110-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">metric =</span> <span class="st">"ROC"</span>,</span>
<span id="cb110-10"><a href="#cb110-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

1553 samples
  12 predictor
   2 classes: 'Gardner', 'Janson' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 1398, 1398, 1398, 1398, 1398, 1398, ... 
Resampling results across tuning parameters:

  cp          ROC        Sens       Spec
  0.00000000  1.0000000  1.0000000  1.0 
  0.06083789  1.0000000  1.0000000  1.0 
  0.12167577  0.9895579  0.9374132  1.0 
  0.18251366  0.8653901  0.7243449  1.0 
  0.24335155  0.8536618  0.7073236  1.0 
  0.30418944  0.8536618  0.7073236  1.0 
  0.36502732  0.8536618  0.7073236  1.0 
  0.42586521  0.8536618  0.7073236  1.0 
  0.48670310  0.8536618  0.7073236  1.0 
  0.54754098  0.6689474  0.8378947  0.5 

ROC was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.06083789.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit<span class="sc">$</span>finalModel, <span class="at">extra =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-73-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> <span class="fu">predict</span>(fit, testing_artists),</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">ref =</span> testing_artists<span class="sc">$</span>book, <span class="at">positive =</span> <span class="st">"Janson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Gardner Janson
   Gardner     942      0
   Janson        0    609
                                     
               Accuracy : 1          
                 95% CI : (0.9976, 1)
    No Information Rate : 0.6074     
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
                                     
                  Kappa : 1          
                                     
 Mcnemar's Test P-Value : NA         
                                     
            Sensitivity : 1.0000     
            Specificity : 1.0000     
         Pos Pred Value : 1.0000     
         Neg Pred Value : 1.0000     
             Prevalence : 0.3926     
         Detection Rate : 0.3926     
   Detection Prevalence : 0.3926     
      Balanced Accuracy : 1.0000     
                                     
       'Positive' Class : Janson     
                                     </code></pre>
</div>
</div>
<section id="create-a-biased-classifier" class="level4">
<h4 class="anchored" data-anchor-id="create-a-biased-classifier">Create A Biased Classifier</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, testing_artists, <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Gardner Janson
1546       0      1
1547       0      1
1548       0      1
1549       0      1
1550       0      1
1551       0      1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(prob[,<span class="st">"Janson"</span>]<span class="sc">&gt;=</span><span class="fl">0.01</span>, <span class="st">"Janson"</span>, <span class="st">"Gardner"</span>))</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> pred,</span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">ref =</span> testing_artists<span class="sc">$</span>book, <span class="at">positive =</span> <span class="st">"Janson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Gardner Janson
   Gardner     942      0
   Janson        0    609
                                     
               Accuracy : 1          
                 95% CI : (0.9976, 1)
    No Information Rate : 0.6074     
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
                                     
                  Kappa : 1          
                                     
 Mcnemar's Test P-Value : NA         
                                     
            Sensitivity : 1.0000     
            Specificity : 1.0000     
         Pos Pred Value : 1.0000     
         Neg Pred Value : 1.0000     
             Prevalence : 0.3926     
         Detection Rate : 0.3926     
   Detection Prevalence : 0.3926     
      Balanced Accuracy : 1.0000     
                                     
       'Positive' Class : Janson     
                                     </code></pre>
</div>
</div>
</section>
<section id="plot-the-roc-curve" class="level4">
<h4 class="anchored" data-anchor-id="plot-the-roc-curve">Plot the ROC Curve</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"pROC"</span>)</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">roc</span>(testing_artists<span class="sc">$</span>book <span class="sc">==</span> <span class="st">"Janson"</span>, prob[,<span class="st">"Janson"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
roc.default(response = testing_artists$book == "Janson", predictor = prob[,     "Janson"])

Data: prob[, "Janson"] in 942 controls (testing_artists$book == "Janson" FALSE) &lt; 609 cases (testing_artists$book == "Janson" TRUE).
Area under the curve: 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggroc</span>(r) <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">1</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"darkgrey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-79-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here area under the curve is 1 creating the perfect diagonal, indicates perfect classification.</p>
</section>
</section>
<section id="option-4-use-a-cost-sensitive-classifier" class="level3">
<h3 class="anchored" data-anchor-id="option-4-use-a-cost-sensitive-classifier">Option 4: Use a Cost-Sensitive Classifier</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>cost <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(</span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span>,   <span class="dv">1</span>,</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span>, <span class="dv">0</span></span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a>), <span class="at">byrow =</span> <span class="cn">TRUE</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a>cost</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    0    1
[2,]  100    0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> training_artists <span class="sc">|&gt;</span> </span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">train</span>(book <span class="sc">~</span> .,</span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> _,</span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb126-5"><a href="#cb126-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">parms =</span> <span class="fu">list</span>(<span class="at">loss =</span> cost),</span>
<span id="cb126-6"><a href="#cb126-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>loss</code> parameter is used to specify the error costs for different classes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

1553 samples
  12 predictor
   2 classes: 'Gardner', 'Janson' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 1398, 1397, 1398, 1397, 1398, 1398, ... 
Resampling results across tuning parameters:

  cp          Accuracy   Kappa    
  0.09672131  0.8872911  0.7755081
  0.17786885  0.8222663  0.6552677
  0.54754098  0.8222663  0.6552677

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.09672131.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit<span class="sc">$</span>finalModel, <span class="at">extra =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-83-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>plotting the graph :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit<span class="sc">$</span>finalModel, <span class="at">extra =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hw-03-01-eshaanmathakari_files/figure-html/unnamed-chunk-84-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> <span class="fu">predict</span>(fit, testing_artists),</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">ref =</span> testing_artists<span class="sc">$</span>book, <span class="at">positive =</span> <span class="st">"Janson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Gardner Janson
   Gardner     744      0
   Janson      198    609
                                          
               Accuracy : 0.8723          
                 95% CI : (0.8547, 0.8886)
    No Information Rate : 0.6074          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.7469          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 1.0000          
            Specificity : 0.7898          
         Pos Pred Value : 0.7546          
         Neg Pred Value : 1.0000          
             Prevalence : 0.3926          
         Detection Rate : 0.3926          
   Detection Prevalence : 0.5203          
      Balanced Accuracy : 0.8949          
                                          
       'Positive' Class : Janson          
                                          </code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>